In [19]:
# Kaggle Dataset

In [20]:
%pip install kagglehub

Requirement already satisfied: kagglehub in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from kagglehub) (0.1.30)
Requirement already satisfied: packaging in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from kagglehub) (26.2)
Requirement already satisfied: pyyaml in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from kagglehub) (4.68.3)
Requirement already satisfied: protobuf in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.35.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from requests->kagglehub) (2026.6.17)
Requirement already satisfied: colorama in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [25]:
%pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
from dotenv import load_dotenv

load_dotenv()

os.environ["KAGGLE_API_TOKEN"] = os.getenv("KAGGLE_API_TOKEN")

Dataset 1 link: https://www.kaggle.com/datasets/alessandrolobello/the-ultimate-earthquake-dataset-from-1990-2023

Dataset 2 link: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database

In [4]:
import kagglehub

# Download latest version
# path = kagglehub.dataset_download("alessandrolobello/the-ultimate-earthquake-dataset-from-1990-2023")
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Jatin Dhiman\.cache\kagglehub\datasets\uciml\pima-indians-diabetes-database\1.archive...

100%|██████████| 8.91k/8.91k [00:00<00:00, 6.49MB/s]

Extracting files...
Path to dataset files: C:\Users\Jatin Dhiman\.cache\kagglehub\datasets\uciml\pima-indians-diabetes-database\versions\1

In [10]:
import shutil

shutil.copytree(
    r"C:\Users\Jatin Dhiman\.cache\kagglehub\datasets\uciml\pima-indians-diabetes-database\versions\1",
    r"C:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\day-6",
    dirs_exist_ok=True
)

'C:\\Users\\Jatin Dhiman\\OneDrive\\Desktop\\Computer-Vision\\day-6'

In [12]:
import pandas as pd

In [13]:
# df = pd.read_csv("/content/dataset/Eartquakes-1990-2023.csv")
df = pd.read_csv("./diabetes.csv")

In [14]:
df.shape

(768, 9)

In [15]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [18]:
# UCI ML Repository Datasets

In [16]:
%pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from ucimlrepo) (3.0.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from ucimlrepo) (2026.6.17)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\Jatin Dhiman\OneDrive\Desktop\Computer-Vision\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

In [21]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is one of the earliest datasets used in the literature on classification methods and widely used in statistics and machine learning.  The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant.  One class is linearly separable from the other 2; the latter are not linearly separable from each other.\n\nPredicted attribute: class of iris plant.\n\nThis is an exceedingly simple domain.\n\nThis data differs from the data presented in Fishers article (identified by Steve Chadwick,  spchadwick@espeedaz.net ).  The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa" where the error is in the fourth feature. The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa" where the errors are in the second and third features.  ', 'purpose': 'N/A', 'funded_by': None, 'instances_represent': 'Each instance is a plant', 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}}
           name     role         type demographic  \
0  sepal length  Feature   Continuous        None
1   sepal width  Feature   Continuous        None
2  petal length  Feature   Continuous        None
3   petal width  Feature   Continuous        None
4         class   Target  Categorical        None

                                         description units missing_values
0                                                NaN    cm             no
1                                                NaN    cm             no
2                                                NaN    cm             no
3                                                NaN    cm             no
4  class of iris plant: Iris Setosa, Iris Versico...   NaN             no

In [22]:
print(type(X))

<class 'pandas.DataFrame'>

In [23]:
X.head()

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [24]:
y.head()

         class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa