**1. Setup**

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import loguniform

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    RandomizedSearchCV
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

**2. Load Data & clean**

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.shape

(768, 9)

**3. Quick checks**

In [5]:
# check missing values
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

**4. Split features & target**

In [6]:
X = df.drop(columns=["Outcome"])
y = df["Outcome"]

In [7]:
X[:5]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [8]:
y[:5]

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

**Model Training, Tuning, and Evaluation Flow**

Full data<br>
↓<br>
Train–test split<br>
↓<br>
GridSearchCV / RandomizedSearchCV<br>
↓<br>
CV Fold 1: fit scaler + model on train fold, validate<br>
↓<br>
CV Fold 2: fit scaler + model on train fold, validate<br>
↓<br>
CV Fold 3: ...<br>
↓<br>
Best hyperparameters selected<br>
↓<br>
Final evaluation on test set (once)

---

**Key**

❌ Cross-validation is NOT done on the full dataset<br>
❌ Test data is NOT used during hyperparameter tuning<br>
<br>
✅ Cross-validation happens only inside the training set<br>
✅ Test set is used only once, at the very end

**5. Train Test Split**

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [10]:
print("Dataset size:", X.shape)
print("Training data size", X_train.shape)
print("Test data size:", X_test.shape)

Dataset size: (768, 8)
Training data size (614, 8)
Test data size: (154, 8)

**6. Pipeline (scaler + model)**

In [11]:
pipeline = Pipeline(
    [
        ("scaler", StandardScaler()),
        ("model", SVC())
    ]
)

**7. GridSearchCV (tries all combinations)**

In [12]:
param_grid = [
    {
        "model__kernel": ["linear"],
        "model__C": [0.1, 1, 10, 100]
    },
    {
        "model__kernel": ["rbf"],
        "model__C": [0.1, 1, 10, 100],
        "model__gamma": ["scale", "auto", 0.01, 0.1,]
    },
    {
        "model__kernel": ["poly"],
        "model__C": [0.1, 1, 10],
        "model__gamma": ["scale", "auto", 0.01, 0.1],
        "model__degree": [2, 3, 4]
    }
]

In [13]:
grid = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    return_train_score=True,
    n_jobs=-1
)

In [14]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', SVC())]),
             n_jobs=-1,
             param_grid=[{'model__C': [0.1, 1, 10, 100],
                          'model__kernel': ['linear']},
                         {'model__C': [0.1, 1, 10, 100],
                          'model__gamma': ['scale', 'auto', 0.01, 0.1],
                          'model__kernel': ['rbf']},
                         {'model__C': [0.1, 1, 10], 'model__degree': [2, 3, 4],
                          'model__gamma': ['scale', 'auto', 0.01, 0.1],
                          'model__kernel': ['poly']}],
             return_train_score=True, scoring='accuracy')

In [15]:
print("GRID SEARCH CV - Results:")
print("Best params:", grid.best_params_)
print("Best CV accuracy:", grid.best_score_)

GRID SEARCH CV - Results:
Best params: {'model__C': 10, 'model__gamma': 0.01, 'model__kernel': 'rbf'}
Best CV accuracy: 0.7785419165667067

In [16]:
# evaluation on global test set (unseen data)
test_accuracy = round(grid.score(X_test, y_test)*100, 2)
print(f"Test Accuracy: {test_accuracy} %")

Test Accuracy: 75.32 %

**Analysing results**

In [17]:
grid.cv_results_

{'mean_fit_time': array([0.03668442, 0.05496535, 0.16081796, 0.50433474, 0.03951435,
        0.04310346, 0.02573366, 0.03428407, 0.03361621, 0.02299738,
        0.02115135, 0.0267695 , 0.03436613, 0.03137226, 0.04354682,
        0.04145756, 0.07589626, 0.07594628, 0.05997329, 0.10300746,
        0.0323813 , 0.02407041, 0.02473741, 0.0224606 , 0.03718915,
        0.03075166, 0.03026938, 0.01999326, 0.02638822, 0.02626667,
        0.02738109, 0.06613941, 0.02661152, 0.02528458, 0.02161469,
        0.03476315, 0.02396321, 0.02306952, 0.02847967, 0.04798827,
        0.04705958, 0.04083252, 0.02988086, 0.03272562, 0.05691648,
        0.09833183, 0.04878945, 0.08654881, 0.08498878, 0.09331012,
        0.02589445, 0.03820419, 0.06035438, 0.04753613, 0.03263106,
        0.0422502 ]),
 'std_fit_time': array([0.00959283, 0.02163246, 0.06943617, 0.09175315, 0.02031546,
        0.02277141, 0.00309482, 0.0220591 , 0.0170362 , 0.00164558,
        0.00081548, 0.00332916, 0.00309477, 0.00356252, 0.04298341,
        0.02867032, 0.04975543, 0.03809879, 0.04288339, 0.05071236,
        0.01591456, 0.00261577, 0.00408195, 0.00226225, 0.02684187,
        0.02033953, 0.02096204, 0.00091679, 0.00317361, 0.00466434,
        0.01043057, 0.04848333, 0.00239684, 0.00158213, 0.0011912 ,
        0.01247823, 0.00338026, 0.00196344, 0.01583537, 0.03885235,
        0.02517749, 0.01091185, 0.00661438, 0.00811231, 0.01233098,
        0.07952368, 0.04108663, 0.06551697, 0.03311034, 0.07786121,
        0.00544212, 0.00437438, 0.03131621, 0.00939594, 0.01903523,
        0.01148414]),
 'mean_score_time': array([0.02565589, 0.01756382, 0.00943999, 0.00906696, 0.01665645,
        0.01856179, 0.01450334, 0.02351503, 0.05216012, 0.01231737,
        0.01486382, 0.01607308, 0.01451631, 0.03007421, 0.01289492,
        0.02569356, 0.04222469, 0.01322241, 0.02930574, 0.03420172,
        0.03176417, 0.00982203, 0.01050014, 0.00861049, 0.00854177,
        0.00821056, 0.01174965, 0.00936842, 0.00847983, 0.00816774,
        0.00880904, 0.00874081, 0.00791092, 0.00972047, 0.00930972,
        0.01727853, 0.00916595, 0.00810122, 0.00874186, 0.00873208,
        0.01230173, 0.01081076, 0.00933056, 0.01143999, 0.00867696,
        0.01069074, 0.02204828, 0.02317381, 0.01964397, 0.02323189,
        0.01073108, 0.00870628, 0.03762093, 0.00904994, 0.01080294,
        0.00933938]),
 'std_score_time': array([0.02697634, 0.01272421, 0.00178675, 0.00127642, 0.00232512,
        0.00354239, 0.00133018, 0.01522476, 0.04804964, 0.00065747,
        0.0030586 , 0.0034753 , 0.0018229 , 0.03209521, 0.0023315 ,
        0.02360724, 0.05100562, 0.00077112, 0.03085425, 0.0392794 ,
        0.04448302, 0.00194796, 0.00166848, 0.00097467, 0.00058835,
        0.0010536 , 0.00573512, 0.00180793, 0.0008323 , 0.00018803,
        0.00089653, 0.00114601, 0.00072258, 0.00122446, 0.00206831,
        0.01489342, 0.00094886, 0.00194506, 0.00134655, 0.00175469,
        0.00842224, 0.00394152, 0.0014555 , 0.00239696, 0.00098491,
        0.00288314, 0.01945591, 0.02297962, 0.02167086, 0.0313097 ,
        0.00313784, 0.00109288, 0.03695324, 0.00158816, 0.00259841,
        0.00087571]),
 'param_model__C': masked_array(data=[0.1, 1.0, 10.0, 100.0, 0.1, 0.1, 0.1, 0.1, 1.0, 1.0,
                    1.0, 1.0, 10.0, 10.0, 10.0, 10.0, 100.0, 100.0, 100.0,
                    100.0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'param_model__kernel': masked_array(data=['linear', 'linear', 'linear', 'linear', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_model__gamma': masked_array(data=[--, --, --, --, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1],
              mask=[ True,  True,  True,  True, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_model__degree': masked_array(data=[--, --, --, --, --, --, --, --, --, --, --, --, --, --,
                    --, --, --, --, --, --, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4,
                    4, 4, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 2, 2, 2, 2,
                    3, 3, 3, 3, 4, 4, 4, 4],
              mask=[ True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'model__C': 0.1, 'model__kernel': 'linear'},
  {'model__C': 1, 'model__kernel': 'linear'},
  {'model__C': 10, 'model__kernel': 'linear'},
  {'model__C': 100, 'model__kernel': 'linear'},
  {'model__C': 0.1, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 0.1, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 0.1, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 0.1, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 0.1,
   'model__kernel': 'poly'}],
 'split0_test_score': array([0.77235772, 0.75609756, 0.75609756, 0.75609756, 0.77235772,
        0.77235772, 0.6504065 , 0.76422764, 0.73170732, 0.73170732,
        0.75609756, 0.7398374 , 0.72357724, 0.72357724, 0.76422764,
        0.69918699, 0.70731707, 0.70731707, 0.71544715, 0.70731707,
        0.65853659, 0.65853659, 0.6504065 , 0.63414634, 0.70731707,
        0.70731707, 0.6504065 , 0.67479675, 0.70731707, 0.70731707,
        0.6504065 , 0.6504065 , 0.71544715, 0.71544715, 0.6504065 ,
        0.72357724, 0.70731707, 0.70731707, 0.6504065 , 0.71544715,
        0.69918699, 0.69918699, 0.6504065 , 0.68292683, 0.69105691,
        0.69105691, 0.63414634, 0.69105691, 0.7398374 , 0.7398374 ,
        0.63414634, 0.73170732, 0.69105691, 0.69105691, 0.64227642,
        0.68292683]),
 'split1_test_score': array([0.7804878 , 0.78861789, 0.78861789, 0.78861789, 0.77235772,
        0.77235772, 0.6504065 , 0.77235772, 0.7398374 , 0.7398374 ,
        0.7804878 , 0.75609756, 0.70731707, 0.70731707, 0.79674797,
        0.77235772, 0.66666667, 0.66666667, 0.7398374 , 0.67479675,
        0.67479675, 0.67479675, 0.6504065 , 0.65853659, 0.69918699,
        0.69918699, 0.6504065 , 0.67479675, 0.65853659, 0.65853659,
        0.6504065 , 0.66666667, 0.72357724, 0.72357724, 0.6504065 ,
        0.69918699, 0.74796748, 0.74796748, 0.6504065 , 0.7398374 ,
        0.71544715, 0.71544715, 0.6504065 , 0.69918699, 0.74796748,
        0.74796748, 0.65853659, 0.73170732, 0.74796748, 0.74796748,
        0.6504065 , 0.70731707, 0.67479675, 0.67479675, 0.6504065 ,
        0.7398374 ]),
 'split2_test_score': array([0.75609756, 0.75609756, 0.75609756, 0.75609756, 0.7398374 ,
        0.7398374 , 0.6504065 , 0.73170732, 0.76422764, 0.76422764,
        0.75609756, 0.7804878 , 0.68292683, 0.68292683, 0.74796748,
        0.69105691, 0.65853659, 0.65853659, 0.76422764, 0.66666667,
        0.65853659, 0.65853659, 0.6504065 , 0.6504065 , 0.68292683,
        0.68292683, 0.6504065 , 0.67479675, 0.69105691, 0.69105691,
        0.6504065 , 0.67479675, 0.67479675, 0.67479675, 0.6504065 ,
        0.68292683, 0.71544715, 0.71544715, 0.6504065 , 0.69105691,
        0.71544715, 0.71544715, 0.6504065 , 0.70731707, 0.70731707,
        0.70731707, 0.6504065 , 0.67479675, 0.73170732, 0.73170732,
        0.6504065 , 0.73170732, 0.69918699, 0.69918699, 0.6504065 ,
        0.69105691]),
 'split3_test_score': array([0.78861789, 0.77235772, 0.77235772, 0.76422764, 0.72357724,
        0.72357724, 0.6504065 , 0.7398374 , 0.77235772, 0.77235772,
        0.7804878 , 0.75609756, 0.73170732, 0.73170732, 0.7804878 ,
        0.7398374 , 0.66666667, 0.66666667, 0.77235772, 0.65853659,
        0.67479675, 0.67479675, 0.6504065 , 0.65853659, 0.71544715,
        0.71544715, 0.6504065 , 0.69105691, 0.69105691, 0.69105691,
        0.6504065 , 0.69105691, 0.66666667, 0.66666667, 0.6504065 ,
        0.67479675, 0.71544715, 0.71544715, 0.6504065 , 0.73170732,
        0.69105691, 0.69105691, 0.6504065 , 0.70731707, 0.69918699,
        0.69918699, 0.65853659, 0.69105691, 0.69918699, 0.69918699,
        0.6504065 , 0.70731707, 0.67479675, 0.67479675, 0.6504065 ,
        0.68292683]),
 'split4_test_score': array([0.79508197, 0.80327869, 0.80327869, 0.80327869, 0.76229508,
        0.76229508, 0.6557377 , 0.76229508, 0.75409836, 0.75409836,
        0.81147541, 0.76229508, 0.77868852, 0.77868852, 0.80327869,
        0.77868852, 0.75409836, 0.75409836, 0.81967213, 0.71311475,
        0.68032787, 0.68032787, 0.6557377 , 0.66393443, 0.76229508,
        0.76229508, 0.6557377 , 0.71311475, 0.72131148, 0.72131148,
        0.6557377 , 0.68032787, 0.71311475, 0.71311475, 0.6557377 ,
        0.73770492, 0.77868852, 0.77868852, 0.6557377 , 0.78688525,
        0.74590164, 0.74590164, 0.6557377 , 0.76229508, 0.7295082 ,
        0.7295082 , 0.66393443, 0.7295082 , 0.79508197, 0.79508197,
        0.6557377 , 0.77868852, 0.69672131, 0.69672131, 0.6557377 ,
        0.7295082 ]),
 'mean_test_score': array([0.77852859, 0.77528988, 0.77528988, 0.77366387, 0.75408503,
        0.75408503, 0.65147274, 0.75408503, 0.75244569, 0.75244569,
        0.77692923, 0.75896308, 0.7248434 , 0.7248434 , 0.77854192,
        0.73622551, 0.69065707, 0.69065707, 0.76230841, 0.68408637,
        0.66939891, 0.66939891, 0.65147274, 0.65311209, 0.71343463,
        0.71343463, 0.65147274, 0.68571238, 0.69385579, 0.69385579,
        0.65147274, 0.67265094, 0.69872051, 0.69872051, 0.65147274,
        0.70363854, 0.73297348, 0.73297348, 0.65147274, 0.73298681,
        0.71340797, 0.71340797, 0.65147274, 0.71180861, 0.71500733,
        0.71500733, 0.65311209, 0.70362522, 0.74275623, 0.74275623,
        0.64822071, 0.73134746, 0.68731174, 0.68731174, 0.64984673,
        0.70525123]),
 'std_test_score': array([0.01357113, 0.01847321, 0.01847321, 0.01900975, 0.01933343,
        0.01933343, 0.00213248, 0.01554301, 0.01501389, 0.01501389,
        0.02042881, 0.01308916, 0.03166129, 0.03166129, 0.02042963,
        0.03614898, 0.03601432, 0.03601432, 0.0349176 , 0.02202202,
        0.00909611, 0.00909611, 0.00213248, 0.01042107, 0.02669284,
        0.02669284, 0.00213248, 0.01507917, 0.02096728, 0.02096728,
        0.00213248, 0.01365977, 0.0232578 , 0.0232578 , 0.00213248,
        0.02382734, 0.02678537, 0.02678537, 0.00213248, 0.03168396,
        0.01879341, 0.01879341, 0.00213248, 0.02676824, 0.02087914,
        0.02087914, 0.01042107, 0.02282778, 0.03096455, 0.03096455,
        0.00733384, 0.02606283, 0.01055308, 0.01055308, 0.00431169,
        0.02442474]),
 'rank_test_score': array([ 2,  4,  4,  6,  9,  9, 48,  9, 12, 12,  3,  8, 21, 21,  1, 16, 37,
        37,  7, 42, 44, 44, 48, 46, 25, 25, 48, 41, 35, 35, 48, 43, 33, 33,
        48, 31, 18, 18, 48, 17, 27, 27, 48, 29, 23, 23, 46, 32, 14, 14, 56,
        20, 39, 39, 55, 30]),
 'split0_train_score': array([0.79633401, 0.80651731, 0.80651731, 0.80651731, 0.79429735,
        0.79429735, 0.65173116, 0.79022403, 0.85336049, 0.85336049,
        0.80244399, 0.84317719, 0.91242363, 0.91242363, 0.80855397,
        0.89613035, 0.97759674, 0.97759674, 0.84114053, 0.96334012,
        0.700611  , 0.700611  , 0.65173116, 0.67820774, 0.75152749,
        0.75152749, 0.65173116, 0.7311609 , 0.74338086, 0.74338086,
        0.65173116, 0.71283096, 0.75152749, 0.75152749, 0.65173116,
        0.7413442 , 0.81059063, 0.81059063, 0.65173116, 0.79633401,
        0.81873727, 0.81873727, 0.65173116, 0.77800407, 0.76985743,
        0.76985743, 0.67820774, 0.76782077, 0.86354379, 0.86354379,
        0.6598778 , 0.85947047, 0.89205703, 0.89205703, 0.65173116,
        0.86354379]),
 'split1_train_score': array([0.78818737, 0.79226069, 0.79226069, 0.79633401, 0.76985743,
        0.76985743, 0.65173116, 0.77393075, 0.83299389, 0.83299389,
        0.78411405, 0.82484725, 0.89205703, 0.89205703, 0.80040733,
        0.87372709, 0.97148676, 0.97148676, 0.81670061, 0.94501018,
        0.67209776, 0.67209776, 0.65173116, 0.6598778 , 0.74338086,
        0.74338086, 0.65173116, 0.71690428, 0.72505092, 0.72505092,
        0.65173116, 0.7107943 , 0.73727088, 0.73727088, 0.65173116,
        0.72708758, 0.80651731, 0.80651731, 0.65173116, 0.79226069,
        0.79837067, 0.79837067, 0.65173116, 0.77393075, 0.74949084,
        0.74949084, 0.6598778 , 0.76171079, 0.86150713, 0.86150713,
        0.65173116, 0.84521385, 0.87576375, 0.87576375, 0.65173116,
        0.84521385]),
 'split2_train_score': array([0.80040733, 0.79837067, 0.79837067, 0.79837067, 0.77596741,
        0.77596741, 0.65173116, 0.78207739, 0.84928717, 0.84928717,
        0.79226069, 0.84114053, 0.91649695, 0.91649695, 0.80855397,
        0.89205703, 0.97148676, 0.97148676, 0.82892057, 0.9592668 ,
        0.6700611 , 0.6700611 , 0.65173116, 0.66395112, 0.73727088,
        0.73727088, 0.65173116, 0.71690428, 0.73319756, 0.73319756,

In [18]:
# gris searcg cv - all cv results

grid_results_df = pd.DataFrame(grid.cv_results_)

# select only the useful columns
grid_results_df = grid_results_df[["params", "mean_train_score", "mean_test_score", "rank_test_score"]].sort_values("rank_test_score")

grid_results_df

,params,mean_train_score,mean_test_score,rank_test_score
14,"{'model__C': 10, 'model__gamma': 0.01, 'model_...",0.800902,0.778542,1
0,"{'model__C': 0.1, 'model__kernel': 'linear'}",0.790718,0.778529,2
10,"{'model__C': 1, 'model__gamma': 0.01, 'model__...",0.789904,0.776929,3
2,"{'model__C': 10, 'model__kernel': 'linear'}",0.794791,0.775290,4
1,"{'model__C': 1, 'model__kernel': 'linear'}",0.795197,0.775290,4
3,"{'model__C': 100, 'model__kernel': 'linear'}",0.795198,0.773664,6
18,"{'model__C': 100, 'model__gamma': 0.01, 'model...",0.827775,0.762308,7
11,"{'model__C': 1, 'model__gamma': 0.1, 'model__k...",0.833473,0.758963,8
4,"{'model__C': 0.1, 'model__gamma': 'scale', 'mo...",0.779728,0.754085,9
5,"{'model__C': 0.1, 'model__gamma': 'auto', 'mod...",0.779728,0.754085,9
7,"{'model__C': 0.1, 'model__gamma': 0.1, 'model_...",0.781355,0.754085,9
8,"{'model__C': 1, 'model__gamma': 'scale', 'mode...",0.843243,0.752446,12
9,"{'model__C': 1, 'model__gamma': 'auto', 'model...",0.843243,0.752446,12
48,"{'model__C': 10, 'model__degree': 3, 'model__g...",0.860755,0.742756,14
49,"{'model__C': 10, 'model__degree': 3, 'model__g...",0.860755,0.742756,14
15,"{'model__C': 10, 'model__gamma': 0.1, 'model__...",0.887219,0.736226,16
39,"{'model__C': 1, 'model__degree': 3, 'model__ga...",0.789908,0.732987,17
37,"{'model__C': 1, 'model__degree': 3, 'model__ga...",0.812708,0.732973,18
36,"{'model__C': 1, 'model__degree': 3, 'model__ga...",0.812708,0.732973,18
51,"{'model__C': 10, 'model__degree': 3, 'model__g...",0.848947,0.731347,20
13,"{'model__C': 10, 'model__gamma': 'auto', 'mode...",0.903913,0.724843,21
12,"{'model__C': 10, 'model__gamma': 'scale', 'mod...",0.903913,0.724843,21
45,"{'model__C': 10, 'model__degree': 2, 'model__g...",0.759773,0.715007,23
44,"{'model__C': 10, 'model__degree': 2, 'model__g...",0.759773,0.715007,23
24,"{'model__C': 0.1, 'model__degree': 3, 'model__...",0.740640,0.713435,25
25,"{'model__C': 0.1, 'model__degree': 3, 'model__...",0.740640,0.713435,25
41,"{'model__C': 1, 'model__degree': 4, 'model__ga...",0.806598,0.713408,27
40,"{'model__C': 1, 'model__degree': 4, 'model__ga...",0.806598,0.713408,27
43,"{'model__C': 1, 'model__degree': 4, 'model__ga...",0.775245,0.711809,29
55,"{'model__C': 10, 'model__degree': 4, 'model__g...",0.854644,0.705251,30
35,"{'model__C': 1, 'model__degree': 2, 'model__ga...",0.734125,0.703639,31
47,"{'model__C': 10, 'model__degree': 2, 'model__g...",0.763030,0.703625,32
32,"{'model__C': 1, 'model__degree': 2, 'model__ga...",0.743897,0.698721,33
33,"{'model__C': 1, 'model__degree': 2, 'model__ga...",0.743897,0.698721,33
29,"{'model__C': 0.1, 'model__degree': 4, 'model__...",0.732902,0.693856,35
28,"{'model__C': 0.1, 'model__degree': 4, 'model__...",0.732902,0.693856,35
17,"{'model__C': 100, 'model__gamma': 'auto', 'mod...",0.973941,0.690657,37
16,"{'model__C': 100, 'model__gamma': 'scale', 'mo...",0.973941,0.690657,37
53,"{'model__C': 10, 'model__degree': 4, 'model__g...",0.884772,0.687312,39
52,"{'model__C': 10, 'model__degree': 4, 'model__g...",0.884772,0.687312,39
27,"{'model__C': 0.1, 'model__degree': 3, 'model__...",0.717838,0.685712,41
19,"{'model__C': 100, 'model__gamma': 0.1, 'model_...",0.956434,0.684086,42
31,"{'model__C': 0.1, 'model__degree': 4, 'model__...",0.711319,0.672651,43
21,"{'model__C': 0.1, 'model__degree': 2, 'model__...",0.675902,0.669399,44
20,"{'model__C': 0.1, 'model__degree': 2, 'model__...",0.675902,0.669399,44
46,"{'model__C': 10, 'model__degree': 2, 'model__g...",0.664092,0.653112,46
23,"{'model__C': 0.1, 'model__degree': 2, 'model__...",0.664092,0.653112,46
6,"{'model__C': 0.1, 'model__gamma': 0.01, 'model...",0.651466,0.651473,48
30,"{'model__C': 0.1, 'model__degree': 4, 'model__...",0.651466,0.651473,48
26,"{'model__C': 0.1, 'model__degree': 3, 'model__...",0.651466,0.651473,48
38,"{'model__C': 1, 'model__degree': 3, 'model__ga...",0.651466,0.651473,48
34,"{'model__C': 1, 'model__degree': 2, 'model__ga...",0.651466,0.651473,48
22,"{'model__C': 0.1, 'model__degree': 2, 'model__...",0.651466,0.651473,48
42,"{'model__C': 1, 'model__degree': 4, 'model__ga...",0.651466,0.651473,48
54,"{'model__C': 10, 'model__degree': 4, 'model__g...",0.651466,0.649847,55
50,"{'model__C': 10, 'model__degree': 3, 'model__g...",0.653096,0.648221,56

In [19]:
len(grid_results_df)

56

**8. Randomized Search CV (random combinations)**

In [20]:
param_dist = [
    # Linear
    {
        "model__kernel": ["linear"],
        "model__C": loguniform(0.01, 100)
    },
 
    # RBF
    {
        "model__kernel": ["rbf"],
        "model__C": loguniform(0.01, 1000),
        "model__gamma": loguniform(0.0001, 10)
    },

    # Poly
    {
        "model__kernel": ["poly"],
        "model__C": loguniform(0.01, 100),
        "model__gamma": loguniform(0.0001, 1),
    }
]

In [21]:
random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring="accuracy",
    random_state=42,
    return_train_score=True,
    n_jobs=-1
)

In [22]:
random_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                             ('model', SVC())]),
                   n_iter=20, n_jobs=-1,
                   param_distributions=[{'model__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002ABB5B50F90>,
                                         'model__kernel': ['linear']},
                                        {'model__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002ABB63BA...
                                         'model__gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002ABB63B8490>,
                                         'model__kernel': ['rbf']},
                                        {'model__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002ABB63B8A50>,
                                         'model__gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000002ABB63BA9D0>,
                                         'model__kernel': ['poly']}],
                   random_state=42, return_train_score=True,
                   scoring='accuracy')

In [23]:
print("Randomized SEARCH CV - Results:")
print("Best params:", random_search.best_params_)
print("Best CV accuracy:", random_search.best_score_)

Randomized SEARCH CV - Results:
Best params: {'model__C': 4.205156450913866, 'model__gamma': 0.01444525102276306, 'model__kernel': 'rbf'}
Best CV accuracy: 0.7850593096094894

In [24]:
# evaluation on global test set (unseen dataset)
test_accuracy = round(random_search.score(X_test, y_test)*100, 2)
print(f"Test accuracy: {test_accuracy} %")

Test accuracy: 74.03 %

In [25]:
# -----------------------------
# RandomizedSearchCV - All CV results
# -----------------------------
random_search_results_df = pd.DataFrame(random_search.cv_results_)

# Select only the most useful columns
random_search_results_df = random_search_results_df[
    [
        "params",
        "mean_train_score",
        "mean_test_score",
        "rank_test_score"
    ]
].sort_values("rank_test_score")

random_search_results_df

,params,mean_train_score,mean_test_score,rank_test_score
7,"{'model__C': 4.205156450913866, 'model__gamma'...",0.799275,0.785059,1
3,"{'model__C': 2.5378155082656657, 'model__kerne...",0.794383,0.775290,2
8,"{'model__C': 1.256315277393867, 'model__kernel...",0.793569,0.775290,2
12,"{'model__C': 0.015339162591163621, 'model__ker...",0.782573,0.773677,4
1,"{'model__C': 2.440060709081755, 'model__kernel...",0.793976,0.773664,5
6,"{'model__C': 2.950706670790534, 'model__kernel...",0.794383,0.773664,5
16,"{'model__C': 26.373339933815235, 'model__gamma...",0.824923,0.763934,7
17,"{'model__C': 2.754143921332031, 'model__gamma'...",0.868490,0.737892,8
10,"{'model__C': 0.6672367170464207, 'model__gamma...",0.809042,0.731361,9
4,"{'model__C': 0.012087541473056965, 'model__gam...",0.835916,0.729708,10
11,"{'model__C': 0.338725556585215, 'model__gamma'...",0.896175,0.716673,11
19,"{'model__C': 1.335916680165182, 'model__gamma'...",0.696269,0.685646,12
14,"{'model__C': 555.1721685244722, 'model__gamma'...",1.000000,0.653099,13
15,"{'model__C': 0.8454394570684998, 'model__gamma...",0.651466,0.651473,14
0,"{'model__C': 15.352246941973492, 'model__gamma...",0.651466,0.651473,14
18,"{'model__C': 43.37920697490943, 'model__gamma'...",0.651466,0.651473,14
5,"{'model__C': 0.1152644954031561, 'model__gamma...",0.651466,0.651473,14
2,"{'model__C': 0.060252157362038566, 'model__gam...",0.651466,0.651473,14
13,"{'model__C': 5.2629610310767445, 'model__gamma...",0.651466,0.651473,14
9,"{'model__C': 0.03613894271216528, 'model__gamm...",0.651466,0.651473,14

In [26]:
random_search_results_df[:1]["params"].values

array([{'model__C': 4.205156450913866, 'model__gamma': 0.01444525102276306, 'model__kernel': 'rbf'}],
      dtype=object)