**1. Setup**

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

**2. Load Data**

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.shape

(768, 9)

In [4]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

** Pima Indians Diabetes Dataset**

| Column Name | Description |
|------------|-------------|
| Pregnancies | Number of times the patient has been pregnant |
| Glucose | Plasma glucose concentration after 2 hours in an oral glucose tolerance test |
| BloodPressure | Diastolic blood pressure (mm Hg) |
| SkinThickness | Thickness of the triceps skin fold (mm) |
| Insulin | 2 hour serum insulin level (mu U/ml) |
| BMI | Body Mass Index (weight in kg / height in m²) |
| DiabetesPedigreeFunction | Likelihood of diabetes based on family history |
| Age | Age of the patient in years |
| Outcome | Target variable indicating diabetes status (1 = Diabetic, 0 = Non Diabetic) |

**3. Quick checks (high-level)**

In [6]:
# missing values
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [8]:
df["Outcome"].value_counts(normalize=True)*100

Outcome
0    65.104167
1    34.895833
Name: proportion, dtype: float64

**4. Split features and target**

In [9]:
X = df.drop(columns=["Outcome"])
y = df["Outcome"]

In [10]:
X[:5]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [11]:
y[:5]

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

**5. Train Test Split**

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [13]:
print("X shape:", X.shape)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X shape: (768, 8)
X_train shape: (614, 8)
X_test shape: (154, 8)

**6. Scale the features**

Fit scaler only on training data, then transform both training and test data

In [14]:
scaler = StandardScaler()

In [15]:
X_train_scaled = scaler.fit_transform(X_train)  # fit & transform
X_test_scaled = scaler.transform(X_test)

In [16]:
print("Preprocessed training data")
print(X_train_scaled.shape)
print(y_train.shape)

print("-"*30)

print("Preprocessed test data")
print(X_test_scaled.shape)
print(y_test.shape)

Preprocessed training data
(614, 8)
(614,)
------------------------------
Preprocessed test data
(154, 8)
(154,)

**7. Model Training**

In [17]:
model = LogisticRegression()

In [18]:
# training the model
model.fit(X_train_scaled, y_train)

LogisticRegression()

**8. Inference**

In [19]:
# training data inference (predictions)
y_train_pred = model.predict(X_train_scaled)

# test data inference
y_test_pred = model.predict(X_test_scaled)

In [20]:
y_train[0:5]

353    0
711    0
373    0
46     0
682    0
Name: Outcome, dtype: int64

In [21]:
y_train_pred[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

**Training data performance**

In [22]:
# comparing true labels and predicted labels for training data
train_accuracy = accuracy_score(y_train, y_train_pred)

In [23]:
train_accuracy

0.7915309446254072

In [24]:
print(f"Training Accuracy {train_accuracy*100:.2f} %")

Training Accuracy 79.15 %

**Test data Performance**

In [25]:
test_accuracy = accuracy_score(y_test, y_test_pred)

In [26]:
print(f"Test Accuracy {test_accuracy*100:.2f} %")

Test Accuracy 71.43 %

| Model Behavior | Training Accuracy | Test Accuracy | Meaning |
|---------------|------------------|---------------|---------|
| Underfitting | Low | Low | Model is too simple and fails to learn patterns |
| Overfitting | High | Much lower | Model memorizes training data and does not generalize |
| Best Fit | High | High (similar) | Model learns general patterns and performs well |

**Interpretation**

In [27]:
# not a hard rule

if train_accuracy < 0.8 and test_accuracy < 0.8:
    print("Model is UNDERFITTING")
elif train_accuracy - test_accuracy > 0.1:
    print("Model is OVERFITTING")
else:
    print("Model is performing well")

Model is UNDERFITTING